services:
  frontend:
    build:
      context: ./AWSUsageScriptFrontEnd
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    container_name: aws-usage-frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5001

  backend:
    build:
      context: ./AWSUsageScriptBackEnd
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    container_name: aws-usage-backend
    volumes:
      - ./data:/app/data
