services:
  frontend:
    build:
      context: ./AWSUsageScriptFrontEnd
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    container_name: aws-usage-frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./AWSUsageScriptBackEnd
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    container_name: aws-usage-backend
    volumes:
      - ./data:/app/data